
import React, { useState } from 'react';
import { Send, Bot, Loader2, AlertCircle } from 'lucide-react';
import { getTaxAdvice } from '../services/geminiService';

export const AIAssistant: React.FC = () => {
  const [query, setQuery] = useState('');
  const [answer, setAnswer] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;
    
    setLoading(true);
    setAnswer(null);
    setError(null);
    
    try {
      const result = await getTaxAdvice(query);
      
      if (result === "CONFIG_ERROR_MISSING_KEY") {
        setError("The API Key hasn't been fully recognized by the production server yet. If you recently added it to Vercel, please trigger a 'Redeploy' from your Vercel Dashboard to ensure the environment variables are active.");
      } else {
        setAnswer(result);
      }
    } catch (err) {
      setError("A connection error occurred. Please try again or contact support.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section id="ai-assistant" className="py-10 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
      <div className="max-w-5xl mx-auto relative z-10">
        <div className="bg-navy/60 backdrop-blur-3xl rounded-[2rem] p-8 md:py-12 md:px-16 shadow-3xl border border-gold/10 transition-all relative overflow-hidden group">
           <div className="text-center mb-8 relative z-10">
            <div className="inline-flex items-center gap-3 px-5 py-1.5 bg-gold/10 rounded-full border border-gold/20 text-gold mb-4 shadow-xl">
              <Bot size={20} />
              <span className="text-[10px] font-bold uppercase tracking-[0.3em]">AI Intelligence</span>
            </div>
            <h2 className="text-3xl md:text-5xl serif text-white font-bold mb-2 tracking-tight">Instant Guidance</h2>
            <p className="text-white/70 max-w-xl mx-auto text-lg font-light leading-relaxed">
              Ask our AI specialist for immediate general guidance on KRA compliance.
            </p>
          </div>

          <div className="relative z-10 max-w-3xl mx-auto">
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="relative group">
                <textarea
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Ex: How do I register for eTIMS in Kenya?"
                  className="w-full p-8 pr-20 rounded-2xl border-2 border-white/5 bg-darker/50 text-white focus:border-gold/50 focus:ring-0 transition-all resize-none h-32 text-lg font-light placeholder:text-white/10 shadow-inner"
                />
                <button
                  type="submit"
                  disabled={loading}
                  className="absolute bottom-6 right-6 bg-gold text-navy p-4 rounded-xl hover:bg-white hover:scale-105 transition-all disabled:opacity-50 shadow-2xl"
                >
                  {loading ? <Loader2 className="animate-spin" size={24} /> : <Send size={24} />}
                </button>
              </div>
            </form>

            {error && (
              <div className="mt-8 p-8 bg-red-900/20 rounded-3xl border border-red-500/30 animate-fade-in flex items-start gap-4">
                <AlertCircle className="text-red-500 mt-1 flex-shrink-0" size={24} />
                <div className="space-y-2">
                  <h4 className="text-white font-bold serif text-lg">AI Assistant Offline</h4>
                  <p className="text-white/70 text-sm leading-relaxed">
                    {error}
                  </p>
                </div>
              </div>
            )}

            {answer && (
              <div className="mt-8 p-10 bg-darker/60 rounded-3xl border border-gold/20 animate-fade-in shadow-2xl">
                <div className="flex items-center gap-5 mb-6">
                  <div className="p-3 bg-gold/10 rounded-xl">
                    <Bot className="text-gold" size={24} />
                  </div>
                  <span className="serif text-xl font-bold text-white tracking-tight">Expert Insight:</span>
                </div>
                <div className="text-white/90 leading-relaxed text-base font-light whitespace-pre-wrap border-l-4 border-gold/30 pl-8">
                  {answer}
                </div>
                <p className="mt-8 text-[10px] text-white/30 uppercase tracking-[0.3em] italic text-center">
                  * Generated by AI. Consult Lucia Maina for legal business finality.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
